Added Spanish translation
MobSF/docs pull request #15
Opened 2022-05-29 04:16 UTC by LinkSake

Hi, I made a version of the Docs in Spanish based on how the other two languages are set up; let me know if it needs some changes.

2022-05-29 07:49 UTC, nelson6e65 commented
Hola, @LinkSake . 👋🏻


I was about to start my translation. It looks good to me. Nice work! 😀

I noticed some minor issues only, but I'll check it better this night when I have more time. 🙂

2022-05-30 16:19 UTC, LinkSake commented
Awesome! Muchas gracias, @nelson6e65!

2022-05-30 17:23 UTC, nelson6e65 requested changes

2022-05-30 17:23 UTC, nelson6e65 commented on es-mx/dynamic_analyzer.md
> +La imagen del emulador de Android con Google Play Store está considerada como una imagen de producción, por ello no se puede usar MobSF con ella.
```suggestion
La imagen del emulador de Android con Google Play Store está considerada como una imagen de producción, por ello no se puede usar MobSF con ella.
Se necesita crear un Dispositivo Android Virtual (AVD) **sin Google Play Store**. No inicies el AVD desde Android Studio, en su lugar inícialo desde la terminal usando la opción `emulador`.
```

2022-05-30 17:23 UTC, nelson6e65 commented on es-mx/dynamic_analyzer.md
> +5. Probar la conección a la máquina virtual de Genymotion Cloud de manera local por medio de ADB.
```suggestion
5. Probar la conexión a la máquina virtual de Genymotion Cloud de manera local por medio de ADB.
```

2022-05-30 17:23 UTC, nelson6e65 commented on es-mx/extras.md
> +**Integraciónes para CI/CD de MobSF**
```suggestion
**Integraciones para CI/CD de MobSF**
```

2022-05-30 17:23 UTC, nelson6e65 commented on es-mx/extras.md
> +Enseguida se deberá de descomentar el siguiente bloque de código:
```suggestion
Seguidamente, deberá de descomentar el siguiente bloque de código:
```

2022-05-30 17:23 UTC, nelson6e65 commented on es-mx/extras.md
> +**Aplicar las Migraciónes**
```suggestion
**Aplicar las Migraciones**
```

2022-05-30 17:23 UTC, nelson6e65 commented on es-mx/extras.md
> +Finalmente es necesario reiniciar el servidor de MobSF, después de ello se habrá configurado de manera éxitosa la nueva base de datos.
```suggestion
Finalmente, es necesario reiniciar el servidor de MobSF, con lo cual se habrá configurado Postgres como tu nueva base de datos de manera exitosa.
```

2022-05-30 17:23 UTC, nelson6e65 commented on es-mx/installation.md
> +!> Se debe de cumplir todos los [requerimientos](/es-mx/requirements.md) previos antes de intentar la instalación de MobSF.
```suggestion
!> Se deben cumplir todos los [requisitos](/es-mx/requirements.md) antes de intentar la instalación de MobSF.
```

2022-05-30 17:23 UTC, nelson6e65 commented on es-mx/requirements.md
> +# Requerimientos Previos
```suggestion
# Requisitos
```

2022-05-30 17:23 UTC, nelson6e65 commented on es-mx/requirements.md
> +* **Distibuciónes de Linux basadas en Ubuntu/Debian**:
```suggestion
* **Distribuciones de Linux basadas en Ubuntu/Debian**:
```

2022-05-30 17:23 UTC, nelson6e65 commented on es-mx/running.md
> +# Correr MobSF
```suggestion
# Ejecutar MobSF
```

2022-05-30 17:23 UTC, nelson6e65 commented on es-mx/tests.md
> +# Corriendo las Pruebas
```suggestion
# Ejecutando las Pruebas
```

2022-05-30 17:23 UTC, nelson6e65 commented on es-mx/updating.md
> +# Actualizando MobSF
```suggestion
# Actualizar MobSF
```

2022-05-30 17:23 UTC, nelson6e65 commented on es-mx/updating.md
> +En la mayor parte de los casos, si se está actualizando MobSF, se deberá de realizar una migración de la base de datos; de lo contrario se podrían presentar errores como el siguiente:
```suggestion
En la mayoría de los casos, si se está actualizando MobSF, se deberá de realizar una migración de la base de datos; de lo contrario se podrían presentar errores como el siguiente:
```

2022-05-30 17:27 UTC, nelson6e65 commented
@LinkSake I added some suggestion and minor fixes. You can use the review “patch” or “batch patches” directly in most of the cases.

2022-05-30 17:47 UTC, nelson6e65 commented
In the other side, it can be used `es` instead of `es-mx`, due to neutral accent.

> Also, "es-419" represents "Spanish as used in Latin America and the Caribbean".

2022-05-30 22:41 UTC, LinkSake commented
> In the other side, it can be used es instead of es-mx, due to neutral accent.
I think you're right! Let me change that real quick.

2022-06-02 14:35 UTC, merged